# Generated by Django 4.2.2 on 2023-06-09 03:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('categoria_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='TipoUsuario',
            fields=[
                ('tipo_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('user', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('mail', models.CharField(max_length=200)),
                ('contrasenna', models.CharField(max_length=15)),
                ('userToken', models.CharField(max_length=30)),
                ('tipo_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PetShop.tipousuario')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('sku', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=44)),
                ('precio', models.IntegerField()),
                ('stock', models.IntegerField()),
                ('descripcion', models.CharField(max_length=115)),
                ('url', models.CharField(max_length=200)),
                ('categoria_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PetShop.categoria')),
            ],
        ),
    ]
